// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtdJmsItKNTQXeG6Yew6JPnvQ-k9INE0Y',
    appId: '1:317047781494:web:888bb5607df714096d4757',
    messagingSenderId: '317047781494',
    projectId: 'mlindemtoto-fbc64',
    authDomain: 'mlindemtoto-fbc64.firebaseapp.com',
    storageBucket: 'mlindemtoto-fbc64.appspot.com',
    measurementId: 'G-TP6FLZLDE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADYsR_Y0rwn23dD8fB3H8kbYmxO3n_TXY',
    appId: '1:317047781494:android:95e5863c44687c016d4757',
    messagingSenderId: '317047781494',
    projectId: 'mlindemtoto-fbc64',
    storageBucket: 'mlindemtoto-fbc64.appspot.com',
  );
}
